### ISSUE TITLE
Didn't overload != in SimpleDoubleLinkedList in Utils/GCFreeList.h

### ISSUE THREAD

**Issue by fenzwu** [dkedyk/ImplementingUsefulAlgorithms#3]
Hi,

I'm curious how this [line](https://github.com/dkedyk/ImplementingUsefulAlgorithms/blob/master/Utils/GCFreeList.h#L62) works if the "!=" operator isn't overloaded? My code wouldn't compile if I didn't overload "!=" for the Iterator class

**Comment by dkedyk** [comment]
Hi Utils.hpp line 42 has a generic operator to implement != in terms of ==

**Comment by fenzwu** [comment]
Thanks!
